let DATA=[]; let filter='all';
const q=document.querySelector('#q'), results=document.querySelector('#results'), status=document.querySelector('#status');
async function init(){const r=await fetch('data/targets.json');DATA=await r.json();render();}
function hay(d){return [d.name,d.scientific,...(d.aliases||[]),...(d.candidates||[]).flatMap(x=>[x.active,x.group,x.system,x.product_example||''])].join(' ').toLowerCase()}
function scopeLabel(s){const m={indonesia_cucumber_verified:'Indonesia ✓',cucumber_global:'Cucumber global',cucurbit_global:'Cucurbit global',vegetable_global:'Sayuran/global',global_candidate:'Kandidat global'};return m[s]||s;}
function render(){const term=q.value.trim().toLowerCase();const list=DATA.filter(d=>(filter==='all'||d.type===filter)&&(!term||hay(d).includes(term)));status.textContent=`${list.length} sasaran ditemukan`;if(!list.length){results.innerHTML='<div class="empty">Tidak ditemukan. Coba nama lain, nama ilmiah, bahan aktif, atau kode grup.</div>';return}results.innerHTML=list.map(d=>`<article class="card"><h2>${d.name}</h2><div class="latin">${d.scientific}</div><p class="summary">${d.summary}</p>${(d.candidates||[]).length?d.candidates.map(c=>`<div class="activeItem"><span class="ai">${c.active}</span><span class="badge ${c.system}">${c.system} ${c.group}</span>${c.scope==='indonesia_cucumber_verified'?'<span class="badge verified">Indonesia ✓</span>':''}<div class="scope">${scopeLabel(c.scope)}${c.product_example?' • contoh: '+c.product_example:''}</div>${c.note?'<div class="note">'+c.note+'</div>':''}</div>`).join(''):'<div class="note">Tidak ada bahan aktif yang direkomendasikan otomatis untuk sasaran ini.</div>'}</article>`).join('');}
q.addEventListener('input',render);
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.page).classList.add('active')});
init().catch(e=>{status.textContent='Gagal memuat data. Jalankan melalui web server/GitHub Pages, bukan file:// langsung.';console.error(e)});
